name: CI Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install flake8 nose

    - name: Lint
      run: flake8 .

    - name: Run tests
      run: nosetests
